# Generated by Django 3.2.3 on 2021-05-21 22:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('type', models.CharField(choices=[('PRI', 'Private'), ('PUB', 'Public')], default=None, max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('birthday', models.DateField(default=None)),
                ('age', models.PositiveIntegerField(default=18, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('nationality', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('N', 'Natural'), ('J', 'Juridico')], default='N', max_length=1)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.bank')),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('minPayment', models.DecimalField(decimal_places=2, max_digits=15)),
                ('maxPayment', models.DecimalField(decimal_places=2, max_digits=15)),
                ('creditMonths', models.IntegerField()),
                ('registryDate', models.DateField(auto_now_add=True)),
                ('type', models.CharField(choices=[('AUT', 'Automotriz'), ('HIP', 'Hipotecarios'), ('COM', 'Comerciales')], default=None, max_length=3, null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.bank')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.client')),
            ],
        ),
    ]
